# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=56, null=True, unique=True)),
                ('level', models.CharField(default='RGLRUSR', editable=False, max_length=7)),
                ('profile', models.TextField(default='User Profile')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('goal', models.TextField(default='Goal')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=56, null=True, unique=True)),
                ('level', models.CharField(default='TRAINER', editable=False, max_length=7)),
                ('profile', models.TextField(default='User Profile')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('past_experience', models.TextField(default='Past Experience')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerAskUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('rglr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RegularAccount')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TrainerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserAskTrainerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('rglr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RegularAccount')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TrainerAccount')),
            ],
        ),
        migrations.AddField(
            model_name='regularaccount',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.TrainerAccount'),
        ),
        migrations.AddField(
            model_name='regularaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
