# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160309_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularaccount',
            name='profile_pic',
            field=models.ImageField(default='http://postimg.org/image/r8k7o4m95/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='traineraccount',
            name='profile_pic',
            field=models.ImageField(default='http://postimg.org/image/r8k7o4m95/', upload_to=''),
        ),
    ]
