# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160321_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAskUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('rglr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RegularAccount')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TrainerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserAskTrainerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('rglr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RegularAccount')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TrainerAccount')),
            ],
        ),
    ]
