# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160319_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularaccount',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
    ]
