# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20160325_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedactivity',
            name='name',
            field=models.TextField(default='Cardial Burning'),
        ),
        migrations.AlterField(
            model_name='savedworkouts',
            name='overview',
            field=models.TextField(default='Standard Workout'),
        ),
    ]
