# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20160325_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedactivity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workouts.Savedworkouts'),
        ),
    ]
