# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20160325_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedactivity',
            old_name='activity_name',
            new_name='name',
        ),
    ]
